version: "3.10"
services:
  api:
    build: .
    environment:
      - ROOT_PATH=${ROOT_PATH}
    command: |
      uvicorn main:app --host 0.0.0.0 --port 5003 --reload --reload-dir ./
    volumes:
      - .:/app
    ports:
      - "5003:5003"
